/**
* _FIPA_Agent_97ImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA_Agent_97.idl
* 08 August 2000 13:41:52 o'clock BST
*/
package fipa97;

public abstract class _FIPA_Agent_97ImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements FIPA_Agent_97, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _FIPA_Agent_97ImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("message", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FIPA_Agent_97/message
       {
         String acl_message = in.read_string ();
         this.message (acl_message);
         out = rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FIPA_Agent_97:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _FIPA_Agent_97ImplBase
