/**
* _FIPA_Agent_97Stub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA_Agent_97.idl
* 08 August 2000 13:12:52 o'clock BST
*/
package fipa97;

public class _FIPA_Agent_97Stub extends org.omg.CORBA.portable.ObjectImpl implements FIPA_Agent_97
{
  // Constructors
  // NOTE:  If the default constructor is used, the
  //        object is useless until _set_delegate (...)
  //        is called.
  public _FIPA_Agent_97Stub ()
  {
    super ();
  }

  public _FIPA_Agent_97Stub (org.omg.CORBA.portable.Delegate delegate)
  {
    super ();
    _set_delegate (delegate);
  }

  public void message (String acl_message)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("message", false);
       _out.write_string (acl_message);
       _in = _invoke (_out);
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       message (acl_message);
    } finally {
        _releaseReply (_in);
    }
  } // message

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FIPA_Agent_97:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s)
  {
     try 
     {
       String str = s.readUTF ();
       org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init ().string_to_object (str);
       org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
       _set_delegate (delegate);
     } catch (java.io.IOException e) {}
  }

  private void writeObject (java.io.ObjectOutputStream s)
  {
     try 
     {
       String str = org.omg.CORBA.ORB.init ().object_to_string (this);
       s.writeUTF (str);
     } catch (java.io.IOException e) {}
  }
} // class _FIPA_Agent_97Stub
