
/**
* FIPA_Agent_97Operations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA_Agent_97.idl
* 08 August 2000 13:41:52 o'clock BST
*/
package fipa97;

public interface FIPA_Agent_97Operations 
{
  void message (String acl_message);
} // interface FIPA_Agent_97Operations
