/**
* FIPA_Agent_97Helper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA_Agent_97.idl
* 08 August 2000 13:12:52 o'clock BST
*/
package fipa97;

abstract public class FIPA_Agent_97Helper
{
  private static String  _id = "IDL:FIPA_Agent_97:1.0";

  public static void insert (org.omg.CORBA.Any a, FIPA_Agent_97 that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FIPA_Agent_97 extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FIPA_Agent_97Helper.id (), "FIPA_Agent_97");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FIPA_Agent_97 read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FIPA_Agent_97Stub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FIPA_Agent_97 value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FIPA_Agent_97 narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FIPA_Agent_97)
      return (FIPA_Agent_97)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new _FIPA_Agent_97Stub (delegate);
    }
  }

}
