
/**
* FIPA_Agent_97Holder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA_Agent_97.idl
* 08 August 2000 13:40:39 o'clock BST
*/
package fipa97;

public final class FIPA_Agent_97Holder implements org.omg.CORBA.portable.Streamable
{
  public FIPA_Agent_97 value = null;

  public FIPA_Agent_97Holder ()
  {
  }

  public FIPA_Agent_97Holder (FIPA_Agent_97 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA_Agent_97Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA_Agent_97Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA_Agent_97Helper.type ();
  }

}
