#!/usr/bin/csh
#This script runs the non-root servers and other utility agents
java zeus.agents.ANServer Nameserver1 -s dns.db & 
java zeus.agents.Facilitator Facilitator1 -o ./test.ont -s dns.db -t 5.0 & 
java zeus.visualiser.Visualiser Visualiser1 -s dns.db -o ./test.ont -quick & 
