/*
	This software was produced as a part of research
	activities. It is not intended to be used as commercial
	or industrial software by any organisation. Except as
	explicitly stated, no guarantees are given as to its
	reliability or trustworthiness if used for purposes other
	than those for which it was originally intended.
 
	(c) British Telecommunications plc 1999.
*/

/*
This stub file was automatically generated by ZeusAgentGenerator version 1.0_b1
*/

import java.util.*;
import zeus.util.*;
import zeus.concepts.*;
import zeus.actors.ZeusTask;
import zeus.actors.*;

public class LookupFaultTable extends ZeusTask {
   protected void exec() {
      /*
      Add the task execution code here. The following variables are defined:
         protected Fact[][]  inputArgs;
         protected Fact[][]  outputArgs;
      Before exec() is called inputArgs will contain the input
      Facts consumed by the task. After execution, set outputArgs to
      contain the output Facts produced by the task.
      */

      // The Input Facts:

      Fact[] _path = inputArgs[0];	// VCPath

      // The Output Facts:

      Fact[] _node_status;	// NodeStatus

      /* USER CODE STARTS */

      _node_status = new Fact[1];
      _node_status[0] = new Fact(Fact.FACT,expOutputArgs[0]);

      for(int i = 0; i < 4; i++ ) {
         String node = _path[0].getValue("element_"+(i+1));
         if ( node.equals("nil") )
            _node_status[0].setValue("status_"+(i+1), "ok");
         else {
            Fact db_template;
            Fact[] data;

            db_template = context.OntologyDb().getFact(Fact.VARIABLE,"NetworkElementStatus");
            db_template.setValue("node",node);
            db_template.setValue("vcid",_path[0].getValue("id"));

            Fact[] db_data = context.ResourceDb().all(db_template);

            if ( (db_data == null) || (db_data.length == 0) )
               _node_status[0].setValue("status_"+(i+1), "ok");
            else {
               double util = db_data[0].getDouble("trunk_utilisation");
               String status = (util > 90) ? "failed" : "ok";
               _node_status[0].setValue("status_"+(i+1),status);
            }
         }
      }
      System.out.println(_node_status[0].pprint());

      /* USER CODE ENDS */
      outputArgs = new Fact[1][];
      outputArgs[0] = _node_status;
   }
}
