package FIPA;

/**
* FIPA/EnvelopeHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA.idl
* 09 March 2001 16:39:32 o'clock GMT
*/

public final class EnvelopeHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.Envelope value = null;

  public EnvelopeHolder ()
  {
  }

  public EnvelopeHolder (FIPA.Envelope initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.EnvelopeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.EnvelopeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.EnvelopeHelper.type ();
  }

}
