package FIPA;


/**
* FIPA/FipaMessage.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA.idl
* 09 March 2001 16:39:32 o'clock GMT
*/

public final class FipaMessage implements org.omg.CORBA.portable.IDLEntity
{
  public FIPA.Envelope messageEnvelopes[] = null;
  public byte messageBody[] = null;

  public FipaMessage ()
  {
  } // ctor

  public FipaMessage (FIPA.Envelope[] _messageEnvelopes, byte[] _messageBody)
  {
    messageEnvelopes = _messageEnvelopes;
    messageBody = _messageBody;
  } // ctor

} // class FipaMessage
