package FIPA;

/**
* FIPA/MTSHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA.idl
* 09 March 2001 16:39:32 o'clock GMT
*/

public final class MTSHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.MTS value = null;

  public MTSHolder ()
  {
  }

  public MTSHolder (FIPA.MTS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.MTSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.MTSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.MTSHelper.type ();
  }

}
