package FIPA;


/**
* FIPA/MTSOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA.idl
* 09 March 2001 16:39:32 o'clock GMT
*/

public interface MTSOperations 
{
  void message (FIPA.FipaMessage aFipaMessage);
} // interface MTSOperations
