package FIPA;


/**
* FIPA/OptAgentIDHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA.idl
* 09 March 2001 16:39:32 o'clock GMT
*/

public final class OptAgentIDHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.AgentID value[] = null;

  public OptAgentIDHolder ()
  {
  }

  public OptAgentIDHolder (FIPA.AgentID[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.OptAgentIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.OptAgentIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.OptAgentIDHelper.type ();
  }

}
