package FIPA;


/**
* FIPA/OptDateTimeHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FIPA.idl
* 09 March 2001 16:39:32 o'clock GMT
*/

public final class OptDateTimeHolder implements org.omg.CORBA.portable.Streamable
{
  public FIPA.DateTime value[] = null;

  public OptDateTimeHolder ()
  {
  }

  public OptDateTimeHolder (FIPA.DateTime[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FIPA.OptDateTimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FIPA.OptDateTimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FIPA.OptDateTimeHelper.type ();
  }

}
