/* Generated By:JavaCC: Do not edit this line. FIPAParserConstants.java */
package zeus.concepts;

public interface FIPAParserConstants {

  int EOF = 0;
  int LBRACKET = 6;
  int RBRACKET = 7;
  int ACCEPT = 8;
  int AGREE = 9;
  int CANCEL = 10;
  int CFP = 11;
  int CONFIRM = 12;
  int DISCONFRIM = 13;
  int FAILURE = 14;
  int INFORM = 15;
  int INFORM_IF = 16;
  int INFORM_REF = 17;
  int NOT_UNDERSTOOD = 18;
  int PROPOSE = 19;
  int QUERY_IF = 20;
  int QUERY_REF = 21;
  int REFUSE = 22;
  int REJECT = 23;
  int REQUEST = 24;
  int REQUEST_WHEN = 25;
  int REQUEST_WHENEVER = 26;
  int REQUEST_FORWARD = 27;
  int SUBSCRIBE = 28;
  int SENDER = 29;
  int RECEIVER = 30;
  int CONTENT = 31;
  int REPLY_WITH = 32;
  int REPLY_BY = 33;
  int IN_REPLY_TO = 34;
  int REPLY_TO = 35;
  int ENVELOPE = 36;
  int LANGUAGE = 37;
  int ONTOLOGY = 38;
  int PROTOCOL = 39;
  int ENCODING = 40;
  int CONVERSATION_ID = 41;
  int NAME = 42;
  int ADDRESSES = 43;
  int SET = 44;
  int AGENT_IDENTIFIER = 45;
  int SEQUENCE = 46;
  int AMS_AGENT_DESC = 47;
  int DF_AGENT_DESC = 48;
  int AP_Description = 49;
  int SEARCH_CONSTRAINTS = 50;
  int OWNERSHIP = 51;
  int STATE = 52;
  int SERVICE_DESCRIPTION = 53;
  int SERVICES = 54;
  int PROPERTIES = 55;
  int PROPERTY = 56;
  int DYNAMIC = 57;
  int MOBILITY = 58;
  int TRANSPORT_PROFILE = 59;
  int MAX_DEPTH = 60;
  int MAX_RESULTS = 61;
  int TYPE = 62;
  int VALUE = 63;
  int AP_TRANSPORT_DESCRIPTION = 64;
  int AVAILABLE_MTS = 65;
  int MTP_DESCRIPTION = 66;
  int PROFILE = 67;
  int MTP_NAME = 68;
  int ALIAS_ADDRESS_OPEN = 69;
  int ZEUS_NAME_OPEN = 70;
  int AID_OPEN = 71;
  int AID_CLOSE = 72;
  int ZEUS_NAME_CLOSE = 73;
  int ALIAS_ADDRESS_CLOSE = 74;
  int TRANSPORT_CONFIGURATION = 75;
  int TRANSPORT_NAME = 76;
  int TRANSPORT_PORT = 77;
  int TRANSPORT_CONFIGURATION_CLOSE = 78;
  int TRANSPORT_NAME_CLOSE = 79;
  int RESOLVERS = 80;
  int TRANSPORT_PORT_CLOSE = 81;
  int GET_DESCRIPTION = 82;
  int REGISTER = 83;
  int SEARCH = 84;
  int DEREGISTER = 85;
  int ONTOLOGIES = 86;
  int LANGUAGES = 87;
  int PROTOCOLS = 88;
  int WORD = 89;
  int INTEGER = 90;
  int ADDR = 91;
  int REAL = 92;
  int DATE_TIME = 93;
  int LITERAL = 94;
  int EXPONENT = 95;
  int LETTER = 96;
  int DIGIT = 97;
  int DECIMAL = 98;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"accept-proposal\"",
    "\"agree\"",
    "\"cancel\"",
    "\"cfp\"",
    "\"confirm\"",
    "\"disconfirm\"",
    "\"failure\"",
    "\"inform\"",
    "\"inform-if\"",
    "\"inform-ref\"",
    "\"not-understood\"",
    "\"propose\"",
    "\"query-if\"",
    "\"query-ref\"",
    "\"refuse\"",
    "\"reject-proposal\"",
    "\"request\"",
    "\"request-when\"",
    "\"request-whenever\"",
    "\"request-forward\"",
    "\"subscribe\"",
    "\":sender\"",
    "\":receiver\"",
    "\":content\"",
    "\":reply-with\"",
    "\":reply-by\"",
    "\":in-reply-to\"",
    "\":reply-to\"",
    "\":envelope\"",
    "\":language\"",
    "\":ontology\"",
    "\":protocol\"",
    "\":encoding\"",
    "\":conversation-id\"",
    "\":name\"",
    "\":addresses\"",
    "\"set\"",
    "\"agent-identifier\"",
    "\"sequence\"",
    "\"ams-agent-description\"",
    "\"df-agent-description\"",
    "\"ap-description\"",
    "\"search-constraints\"",
    "\":ownership\"",
    "\":state\"",
    "\"service-description\"",
    "\":services\"",
    "\":properties\"",
    "\"property\"",
    "\":dynamic\"",
    "\":mobility\"",
    "\":transport-profile\"",
    "\":max-depth\"",
    "\":max-results\"",
    "\":type\"",
    "\":value\"",
    "\"ap-transport-description\"",
    "\":available-mtps\"",
    "\"mtp-description\"",
    "\":profile\"",
    "\":mtp-name\"",
    "\"<alias_address>\"",
    "\"<zeus_name>\"",
    "\"<aid>\"",
    "\"</aid>\"",
    "\"</zeus_name>\"",
    "\"</alias_address>\"",
    "\"<transport_configuration>\"",
    "<TRANSPORT_NAME>",
    "<TRANSPORT_PORT>",
    "\"</transport_configuration>\"",
    "<TRANSPORT_NAME_CLOSE>",
    "<RESOLVERS>",
    "<TRANSPORT_PORT_CLOSE>",
    "\"get-description\"",
    "\"register\"",
    "\"search\"",
    "\"deregister\"",
    "\":ontologies\"",
    "\":languages\"",
    "\":protocols\"",
    "<WORD>",
    "<INTEGER>",
    "<ADDR>",
    "<REAL>",
    "<DATE_TIME>",
    "<LITERAL>",
    "<EXPONENT>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL>",
  };

}
