/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package zeus.concepts;

public interface ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int EQ = 13;
  int LE = 14;
  int GE = 15;
  int NE = 16;
  int GT = 17;
  int LT = 18;
  int PLUS = 19;
  int MINUS = 20;
  int MULTIPLY = 21;
  int DIVIDE = 22;
  int REMAINDER = 23;
  int POWER = 24;
  int AND = 25;
  int OR = 26;
  int NOT = 27;
  int UNOT = 28;
  int UAND = 29;
  int UOR = 30;
  int LBRACKET = 31;
  int RBRACKET = 32;
  int LCURLY = 33;
  int RCURLY = 34;
  int COMMA = 35;
  int TCOLON = 36;
  int VCHR = 37;
  int CCHR = 38;
  int ASEP = 39;
  int IMPLIES = 40;
  int FACT_MARKER = 41;
  int IF = 42;
  int THEN = 43;
  int ELSE = 44;
  int ATTRIBUTE = 45;
  int VALUE = 46;
  int RESTRICTIONS = 47;
  int TYPE = 48;
  int FID = 49;
  int MODIFIERS = 50;
  int ATTRIBUTES = 51;
  int AGENT = 52;
  int ABILITY = 53;
  int FACT = 54;
  int TIME = 55;
  int COST = 56;
  int RELATION = 57;
  int ABILITIES = 58;
  int NAME = 59;
  int HOST = 60;
  int PORT = 61;
  int CLASS = 62;
  int PLANNER_WIDTH = 63;
  int PLANNER_LENGTH = 64;
  int DOUBLE_BOOK_FRACTION = 65;
  int TASKS = 66;
  int PRIMITIVE = 67;
  int SUMMARY = 68;
  int BEHAVIOUR = 69;
  int SCRIPT = 70;
  int INITIAL_FACTS = 71;
  int PROTOCOLS = 72;
  int STRATEGY = 73;
  int PARAMETERS = 74;
  int AGENTS = 75;
  int RELATIONS = 76;
  int ACQUAINTANCES = 77;
  int LHS = 78;
  int RHS = 79;
  int PRODUCER = 80;
  int CONSUMER = 81;
  int PRODUCER_ID = 82;
  int CONSUMER_ID = 83;
  int USE_REF = 84;
  int COMMS_KEY = 85;
  int START = 86;
  int AMOUNT = 87;
  int CONSUMED = 88;
  int STATUS = 89;
  int IMAGE = 90;
  int INVOCATIONS = 91;
  int DESIRED = 92;
  int START_TIME = 93;
  int END_TIME = 94;
  int PRIORITY = 95;
  int ROOT_ID = 96;
  int MEDIA = 97;
  int REPLY_TIME = 98;
  int CONFIRM_TIME = 99;
  int USER_DATA_TYPE = 100;
  int USER_DATA = 101;
  int CONTEXT = 102;
  int GIVEN = 103;
  int PRODUCER_RECORDS = 104;
  int CONSUMER_RECORDS = 105;
  int SUPPLY_REF = 106;
  int HASHTABLE = 107;
  int OWNER = 108;
  int ITEM = 109;
  int OK = 110;
  int IMAGES = 111;
  int VECTOR = 112;
  int EXTERNAL = 113;
  int TABLE = 114;
  int GOALS = 115;
  int ASSERT_GOAL = 116;
  int MESSAGE = 117;
  int INTERNAL = 118;
  int TIMEOUT = 119;
  int DECOMPOSITIONS = 120;
  int CONSUMED_FACTS = 121;
  int PRODUCED_FACTS = 122;
  int CONSTRAINTS = 123;
  int ORDERING = 124;
  int GROUP = 125;
  int IS_CONDITIONAL = 126;
  int IS_AUTORUN = 127;
  int GOAL = 128;
  int TASK = 129;
  int STATE = 130;
  int PARENT = 131;
  int CHILDREN = 132;
  int SIBLINGS = 133;
  int PARENTS = 134;
  int GOAL_ID = 135;
  int LINK = 136;
  int SUPPLIER = 137;
  int RESERVATIONS = 138;
  int NODES = 139;
  int LINKS = 140;
  int LEFT_NODE = 141;
  int LEFT_GROUP = 142;
  int LEFT_ARG = 143;
  int RIGHT_NODE = 144;
  int RIGHT_GROUP = 145;
  int RIGHT_ARG = 146;
  int TEST = 147;
  int NEGATION = 148;
  int ASSERT = 149;
  int SEND_MESSAGE = 150;
  int EXECUTE = 151;
  int ACHIEVE = 152;
  int BUY = 153;
  int SELL = 154;
  int RETRACT = 155;
  int MODIFY = 156;
  int PRINT = 157;
  int PRINTLN = 158;
  int BIND = 159;
  int WHILE = 160;
  int DO = 161;
  int OPEN = 162;
  int CLOSE = 163;
  int SYSTEM_CALL = 164;
  int READ = 165;
  int READLN = 166;
  int CALL = 167;
  int GENERATE = 168;
  int DATABASE = 169;
  int HAS_GUI = 170;
  int ZEUS_EXTERNAL = 171;
  int DNS_FILE = 172;
  int IS_ROOT = 173;
  int ADDRESS_OUTPUT_FILE = 174;
  int TIME_GRAIN = 175;
  int PERIOD = 176;
  int ONTOLOGY = 177;
  int PATH = 178;
  int BEGIN_GENERATOR = 179;
  int BEGIN_PREAMBLE = 180;
  int SYSTEM = 181;
  int VERSION = 182;
  int END_PREAMBLE = 183;
  int BEGIN_AGENT_NAME_INDEX = 184;
  int END_AGENT_NAME_INDEX = 185;
  int BEGIN_AGENT_ICON_INDEX = 186;
  int END_AGENT_ICON_INDEX = 187;
  int BEGIN_TASK_NAME_INDEX = 188;
  int END_TASK_NAME_INDEX = 189;
  int BEGIN_AGENT_LIST = 190;
  int END_AGENT_LIST = 191;
  int BEGIN_TASK_LIST = 192;
  int END_TASK_LIST = 193;
  int BEGIN_GENERATIONPLAN = 194;
  int END_GENERATIONPLAN = 195;
  int PLATFORM = 196;
  int DIRECTORY = 197;
  int BEGIN_NAMESERVER_LIST = 198;
  int END_NAMESERVER_LIST = 199;
  int BEGIN_FACILITATOR_LIST = 200;
  int END_FACILITATOR_LIST = 201;
  int BEGIN_VISUALISER_LIST = 202;
  int END_VISUALISER_LIST = 203;
  int BEGIN_DBPROXY_LIST = 204;
  int END_DBPROXY_LIST = 205;
  int END_GENERATOR = 206;
  int OPAQUE = 207;
  int BOOLEAN = 208;
  int ID = 209;
  int INTEGER = 210;
  int REAL = 211;
  int DATE = 212;
  int TIMEFN = 213;
  int LITERAL = 214;
  int VARIABLE = 215;
  int OBJECT = 216;
  int FIELD = 217;
  int EXPONENT = 218;
  int LETTER = 219;
  int DIGIT = 220;
  int DECIMAL = 221;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"~\"",
    "\"&\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"::\"",
    "\"?\"",
    "\"@\"",
    "\".\"",
    "\"=>\"",
    "\"<-\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\":attribute\"",
    "\":value\"",
    "\":restrictions\"",
    "\":type\"",
    "\":id\"",
    "\":modifiers\"",
    "\":attributes\"",
    "\":agent\"",
    "\":ability\"",
    "\":fact\"",
    "\":time\"",
    "\":cost\"",
    "\":relation\"",
    "\":abilities\"",
    "\":name\"",
    "\":host\"",
    "\":port\"",
    "\":class\"",
    "\":planner_width\"",
    "\":planner_length\"",
    "\":doublebook_fraction\"",
    "\":tasks\"",
    "\":Primitive\"",
    "\":Summary\"",
    "\":Rulebase\"",
    "\":PlanScript\"",
    "\":initial_facts\"",
    "\":protocols\"",
    "\":strategy\"",
    "\":parameters\"",
    "\":agents\"",
    "\":relations\"",
    "\":acquaintances\"",
    "\":lhs\"",
    "\":rhs\"",
    "\":producer\"",
    "\":consumer\"",
    "\":producer_id\"",
    "\":consumer_id\"",
    "\":use_ref\"",
    "\":comms_key\"",
    "\":start\"",
    "\":amount\"",
    "\":consumed\"",
    "\":status\"",
    "\":image\"",
    "\":invocations\"",
    "\":desired_by\"",
    "\":start_time\"",
    "\":end_time\"",
    "\":priority\"",
    "\":root_id\"",
    "\":media\"",
    "\":reply_time\"",
    "\":confirm_time\"",
    "\":user_data_type\"",
    "\":user_data\"",
    "\":context\"",
    "\":given\"",
    "\":producer_records\"",
    "\":consumer_records\"",
    "\":supply_ref\"",
    "\":hashtable\"",
    "\":owner\"",
    "\":item\"",
    "\":ok\"",
    "\":images\"",
    "\":vector\"",
    "\":external\"",
    "\":table\"",
    "\":goals\"",
    "\"Goal\"",
    "\"Message\"",
    "\":internal\"",
    "\":timeout\"",
    "\":decompositions\"",
    "\":consumed_facts\"",
    "\":produced_facts\"",
    "\":constraints\"",
    "\":ordering\"",
    "\":group\"",
    "\":is_conditional\"",
    "\":is_autorun\"",
    "\":goal\"",
    "\":task\"",
    "\":state\"",
    "\":parent\"",
    "\":children\"",
    "\":siblings\"",
    "\":parents\"",
    "\":goal_id\"",
    "\":link\"",
    "\":supplier\"",
    "\":reservations\"",
    "\":nodes\"",
    "\":links\"",
    "\":left_node\"",
    "\":left_group\"",
    "\":left_arg\"",
    "\":right_node\"",
    "\":right_group\"",
    "\":right_arg\"",
    "\"test\"",
    "\"not\"",
    "\"assert\"",
    "\"send_message\"",
    "\"execute\"",
    "\"achieve\"",
    "\"buy\"",
    "\"sell\"",
    "\"retract\"",
    "\"modify\"",
    "\"print\"",
    "\"println\"",
    "\"bind\"",
    "\"while\"",
    "\"do\"",
    "\"open\"",
    "\"close\"",
    "\"system\"",
    "\"read\"",
    "\"readln\"",
    "\"call\"",
    "\":generate\"",
    "\":database\"",
    "\":has_gui\"",
    "\":zeus_external\"",
    "\":dns_file\"",
    "\":is_root\"",
    "\":address_output_file\"",
    "\":time_grain\"",
    "\":period\"",
    "\":ontology\"",
    "\":path\"",
    "\"BEGIN_GENERATOR\"",
    "\"BEGIN_PREAMBLE\"",
    "\":system\"",
    "\":version\"",
    "\"END_PREAMBLE\"",
    "\"BEGIN_AGENT_NAME_INDEX\"",
    "\"END_AGENT_NAME_INDEX\"",
    "\"BEGIN_AGENT_ICON_INDEX\"",
    "\"END_AGENT_ICON_INDEX\"",
    "\"BEGIN_TASK_NAME_INDEX\"",
    "\"END_TASK_NAME_INDEX\"",
    "\"BEGIN_AGENT_LIST\"",
    "\"END_AGENT_LIST\"",
    "\"BEGIN_TASK_LIST\"",
    "\"END_TASK_LIST\"",
    "\"BEGIN_GENERATION_PLAN\"",
    "\"END_GENERATION_PLAN\"",
    "\":platform\"",
    "\":directory\"",
    "\"BEGIN_NAMESERVER_LIST\"",
    "\"END_NAMESERVER_LIST\"",
    "\"BEGIN_FACILITATOR_LIST\"",
    "\"END_FACILITATOR_LIST\"",
    "\"BEGIN_VISUALISER_LIST\"",
    "\"END_VISUALISER_LIST\"",
    "\"BEGIN_DBPROXY_LIST\"",
    "\"END_DBPROXY_LIST\"",
    "\"END_GENERATOR\"",
    "<OPAQUE>",
    "<BOOLEAN>",
    "<ID>",
    "<INTEGER>",
    "<REAL>",
    "<DATE>",
    "<TIMEFN>",
    "<LITERAL>",
    "<VARIABLE>",
    "<OBJECT>",
    "<FIELD>",
    "<EXPONENT>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL>",
  };

}
