/* Generated By:JavaCC: Do not edit this line. PerformativeParserConstants.java */
package zeus.concepts;

public interface PerformativeParserConstants {

  int EOF = 0;
  int LBRACKET = 6;
  int RBRACKET = 7;
  int ACCEPT = 8;
  int AGREE = 9;
  int CANCEL = 10;
  int CFP = 11;
  int CONFIRM = 12;
  int DISCONFRIM = 13;
  int FAILURE = 14;
  int INFORM = 15;
  int INFORM_IF = 16;
  int INFORM_REF = 17;
  int NOT_UNDERSTOOD = 18;
  int PROPOSE = 19;
  int QUERY_IF = 20;
  int QUERY_REF = 21;
  int REFUSE = 22;
  int REJECT = 23;
  int REQUEST = 24;
  int REQUEST_WHEN = 25;
  int REQUEST_WHENEVER = 26;
  int REQUEST_FORWARD = 27;
  int SUBSCRIBE = 28;
  int SENDER = 29;
  int RECEIVER = 30;
  int CONTENT = 31;
  int REPLY_WITH = 32;
  int REPLY_BY = 33;
  int IN_REPLY_TO = 34;
  int REPLY_TO = 35;
  int ENVELOPE = 36;
  int LANGUAGE = 37;
  int ONTOLOGY = 38;
  int PROTOCOL = 39;
  int CONVERSATION_ID = 40;
  int NAME = 41;
  int ADDRESSES = 42;
  int WORD = 43;
  int INTEGER = 44;
  int REAL = 45;
  int DATE_TIME = 46;
  int LITERAL = 47;
  int EXPONENT = 48;
  int LETTER = 49;
  int DIGIT = 50;
  int DECIMAL = 51;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"accept-proposal\"",
    "\"agree\"",
    "\"cancel\"",
    "\"cfp\"",
    "\"confirm\"",
    "\"disconfirm\"",
    "\"failure\"",
    "\"inform\"",
    "\"inform-if\"",
    "\"inform-ref\"",
    "\"not-understood\"",
    "\"propose\"",
    "\"query-if\"",
    "\"query-ref\"",
    "\"refuse\"",
    "\"reject-proposal\"",
    "\"request\"",
    "\"request-when\"",
    "\"request-whenever\"",
    "\"request-forward\"",
    "\"subscribe\"",
    "\":sender\"",
    "\":receiver\"",
    "\":content\"",
    "\":reply-with\"",
    "\":reply-by\"",
    "\":in-reply-to\"",
    "\":reply-to\"",
    "\":envelope\"",
    "\":language\"",
    "\":ontology\"",
    "\":protocol\"",
    "\":conversation-id\"",
    "\":name\"",
    "\":addresses\"",
    "<WORD>",
    "<INTEGER>",
    "<REAL>",
    "<DATE_TIME>",
    "<LITERAL>",
    "<EXPONENT>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL>",
    "\"@\"",
  };

}
