#!/usr/bin/csh
#This script runs the task agents
java TestAgent -o ./messageSpeedTest.ont -s dns.db -gui zeus.agentviewer.AgentViewer -e zeus.test.scaleability.agencySize.singleMachine.TestExternal & 
