#!/usr/bin/csh
#This script runs the non-root servers and other utility agents
java zeus.agents.Facilitator Facilitator0 -o ./messageSpeedTest.ont -s dns.db -t 5.0 & 
java zeus.visualiser.Visualiser Visualiser0 -s dns.db -o ./messageSpeedTest.ont -quick & 
